/**
 * @doccloak/core/dom - detection-driven office file redaction (T110).
 *
 * Ties the format modules (docx.ts, xlsx.ts) to the detection pipeline and an
 * AnonymizationSession, so a host can hand over a File plus its live session
 * and get back a redacted copy whose placeholders are consistent with every
 * prompt redacted in the same session: an AI reply that mentions the file's
 * placeholders restores through the same session map.
 *
 * PDF is intentionally NOT handled here: layout-preserving PDF redaction is
 * out of scope for this module.
 */

import type { DetectedEntity } from '../types.ts';
import type { AnonymizationSession } from '../session.ts';
import type { ValueReplacement } from '../docx.ts';
import { getFileExtension, readDocx, writeAnonymizedDocx } from './docx.ts';
import type { DocxExtraction } from './docx.ts';
import { readXlsx, writeAnonymizedXlsx } from './xlsx.ts';
import type { XlsxExtraction } from './xlsx.ts';

/** File kinds the office redaction flow can regenerate. */
export type OfficeFileKind = 'docx' | 'xlsx';

/**
 * Classify a filename into a supported office kind, or null when the format
 * cannot be regenerated by this module (.doc has its own binary writer in
 * src/doc.ts; PDF output is permanently out of scope for browser hosts).
 */
export function officeFileKind(filename: string): OfficeFileKind | null {
  const ext = getFileExtension(filename);
  if (ext === 'docx') return 'docx';
  if (ext === 'xlsx') return 'xlsx';
  return null;
}

/** A detect function, typically DocCloakEngine.detect or detectEntities. */
export type DetectFn = (text: string) => Promise<DetectedEntity[]>;

export interface OfficeAnalysis {
  kind: OfficeFileKind;
  /** Flat text extracted from every text-bearing part of the package */
  plainText: string;
  /** Entities detected in the flat text (offsets refer to plainText) */
  entities: DetectedEntity[];
}

/**
 * Extract a file's text and run detection WITHOUT touching the session. Hosts
 * use this to show the user what was found before asking for consent to
 * regenerate; a cancelled upload then leaves no trace in the session map.
 * Extraction is deterministic, so entities returned here can be passed to
 * redactOfficeFile later and land on identical offsets.
 */
export async function analyzeOfficeFile(file: File, detect: DetectFn): Promise<OfficeAnalysis> {
  const kind = officeFileKind(file.name);
  if (!kind) throw new Error(`Unsupported office file: ${file.name}`);
  const plainText = kind === 'docx'
    ? (await readDocx(file)).plainText
    : (await readXlsx(file)).plainText;
  const entities = await detect(plainText);
  return { kind, plainText, entities };
}

export interface RedactOfficeFileOptions {
  /** The live session; file placeholders join the same map as prompt ones. */
  session: AnonymizationSession;
  /**
   * Entities to redact, from a prior analyzeOfficeFile call (offsets refer to
   * that call's plainText). When omitted, detect is required and is run here.
   */
  entities?: DetectedEntity[];
  /** Detect function; used only when entities were not supplied. */
  detect?: DetectFn;
  /** Accept and strip tracked changes in docx output. Default: true. */
  acceptTrackedChanges?: boolean;
}

export interface OfficeRedactionResult {
  kind: OfficeFileKind;
  /** The redacted file; the input file/buffer is never modified. */
  blob: Blob;
  /** Suggested output name: "report.docx" becomes "report.redacted.docx". */
  suggestedName: string;
  /** The entities that were redacted (offsets refer to plainText) */
  entities: DetectedEntity[];
  /** Flat text the detection ran on */
  plainText: string;
  /** The redacted flat text (placeholders applied), for preview UIs */
  redactedText: string;
}

/** "report.docx" -> "report.redacted.docx"; extensionless names get a suffix. */
export function redactedFileName(filename: string): string {
  const dot = filename.lastIndexOf('.');
  if (dot <= 0) return `${filename}.redacted`;
  return `${filename.slice(0, dot)}.redacted${filename.slice(dot)}`;
}

/**
 * Redact a DOCX or XLSX file: extract text, detect (or reuse supplied
 * entities), map every entity through the session, and regenerate the file
 * with placeholders spliced into the XML, formatting preserved and metadata
 * stripped. Placeholder issuing goes through session.anonymize, so a value
 * already seen in a prompt reuses its existing placeholder and vice versa.
 */
export async function redactOfficeFile(
  file: File,
  options: RedactOfficeFileOptions
): Promise<OfficeRedactionResult> {
  const kind = officeFileKind(file.name);
  if (!kind) throw new Error(`Unsupported office file: ${file.name}`);

  const extraction = kind === 'docx' ? await readDocx(file) : await readXlsx(file);
  const plainText = extraction.plainText;

  let entities = options.entities;
  if (!entities) {
    if (!options.detect) {
      throw new Error('redactOfficeFile requires either entities or a detect function');
    }
    entities = await options.detect(plainText);
  }

  const { session } = options;

  // Drop entities whose offsets do not match this extraction (defensive: a
  // stale analysis of a different file must not splice garbage), then map
  // through the session in reading order. Surrogate mode maps PERSON values
  // first, mirroring AnonymizationSession.anonymizeText, so derived
  // surrogates (emails from owner names) stay consistent with prompts.
  const valid = entities
    .filter((e) => e.start >= 0 && e.end <= plainText.length && e.start < e.end
      && plainText.slice(e.start, e.end) === e.value)
    .sort((a, b) => a.start - b.start || a.end - b.end);

  if (session.getMode() === 'surrogate') {
    for (const entity of valid) {
      if (entity.type === 'PERSON') session.anonymize(entity.value, entity.type);
    }
  }

  const replacements = valid.map((entity) => ({
    start: entity.start,
    end: entity.end,
    replacement: session.anonymize(entity.value, entity.type),
  }));

  // Value-level scrubbing (relationship targets, formulas, field instructions)
  // uses the whole session map, so a value redacted in an earlier prompt is
  // also caught when it hides in a hyperlink target of this file.
  const valueReplacements: ValueReplacement[] = session.getEntries()
    .filter((entry) => entry.replacement !== '________')
    .map((entry) => ({ value: entry.original, replacement: entry.replacement }));

  let redactedText = plainText;
  for (const repl of [...replacements].sort((a, b) => b.start - a.start)) {
    redactedText = redactedText.slice(0, repl.start) + repl.replacement + redactedText.slice(repl.end);
  }

  const blob = kind === 'docx'
    ? await writeAnonymizedDocx(extraction as DocxExtraction, replacements, valueReplacements, {
        acceptTrackedChanges: options.acceptTrackedChanges ?? true,
      })
    : await writeAnonymizedXlsx(extraction as XlsxExtraction, replacements, valueReplacements);

  return {
    kind,
    blob,
    suggestedName: redactedFileName(file.name),
    entities: valid,
    plainText,
    redactedText,
  };
}
