/**
 * @doccloak/core/dom - detection-driven office file redaction (T110).
 *
 * Ties the format modules (docx.ts, xlsx.ts) to the detection pipeline and an
 * AnonymizationSession, so a host can hand over a File plus its live session
 * and get back a redacted copy whose placeholders are consistent with every
 * prompt redacted in the same session: an AI reply that mentions the file's
 * placeholders restores through the same session map.
 *
 * PDF is intentionally NOT handled here: layout-preserving PDF redaction is
 * out of scope for this module.
 */

import type { DetectedEntity } from '../types.ts';
import type { AnonymizationSession } from '../session.ts';
import type { ValueReplacement } from '../docx.ts';
import { getFileExtension, readDocx, writeAnonymizedDocxWithReport } from './docx.ts';
import type { DocxExtraction } from './docx.ts';
import { readXlsx, writeAnonymizedXlsxWithReport } from './xlsx.ts';
import type { XlsxExtraction } from './xlsx.ts';
import { layerZeroValueReplacements } from './opc.ts';
import type { UnredactablePart } from './errors.ts';

/** File kinds the office redaction flow can regenerate. */
export type OfficeFileKind = 'docx' | 'xlsx';

/**
 * Classify a filename into a supported office kind, or null when the format
 * cannot be regenerated by this module (.doc has its own binary writer in
 * src/doc.ts; PDF output is permanently out of scope for browser hosts).
 */
export function officeFileKind(filename: string): OfficeFileKind | null {
  const ext = getFileExtension(filename);
  if (ext === 'docx') return 'docx';
  if (ext === 'xlsx') return 'xlsx';
  return null;
}

/** A detect function, typically DocCloakEngine.detect or detectEntities. */
export type DetectFn = (text: string) => Promise<DetectedEntity[]>;

/**
 * Raised by redactOfficeFile (T179, finding M4) when supplied entities do
 * not match the file's freshly extracted text: the analysis is stale or came
 * from a different file. Before T179 such entities were dropped silently and
 * the host received a "successful" copy that still held the value.
 *
 * `entities` lists every mismatch (value, type, offsets); the message only
 * counts them and names their types and offsets so it can be logged without
 * repeating the values. The session is not touched when this is thrown.
 */
export class StaleAnalysisError extends Error {
  readonly entities: DetectedEntity[];

  constructor(entities: DetectedEntity[], total: number = entities.length) {
    const where = entities.map((e) => `${e.type}@${e.start}-${e.end}`).join(', ');
    super(
      `${entities.length} of ${total} supplied entities do not match the file's text `
      + `(stale analysis or a different file): ${where}. Re-run analyzeOfficeFile on this file.`,
    );
    this.name = 'StaleAnalysisError';
    this.entities = entities;
    Object.setPrototypeOf(this, new.target.prototype);
  }
}

/** True when `err` is a StaleAnalysisError (also across realms). */
export function isStaleAnalysisError(err: unknown): err is StaleAnalysisError {
  return err instanceof StaleAnalysisError
    || (typeof err === 'object' && err !== null && (err as { name?: string }).name === 'StaleAnalysisError');
}

export interface OfficeAnalysis {
  kind: OfficeFileKind;
  /** Flat text extracted from every text-bearing part of the package */
  plainText: string;
  /** Entities detected in the flat text (offsets refer to plainText) */
  entities: DetectedEntity[];
  /**
   * Parts DocCloak cannot redact (embedded objects, macros, HTML chunks,
   * printer settings, unknown parts; T177). Non-empty means redactOfficeFile
   * refuses the file unless allowUnredactable is passed; hosts show the list
   * and ask before doing so.
   */
  unredactable: UnredactablePart[];
  /** Reader notes: parts skipped by the extractor (malformed XML). */
  warnings: string[];
}

/**
 * Extract a file's text and run detection WITHOUT touching the session. Hosts
 * use this to show the user what was found before asking for consent to
 * regenerate; a cancelled upload then leaves no trace in the session map.
 * Extraction is deterministic, so entities returned here can be passed to
 * redactOfficeFile later and land on identical offsets.
 */
export async function analyzeOfficeFile(file: File, detect: DetectFn): Promise<OfficeAnalysis> {
  const kind = officeFileKind(file.name);
  if (!kind) throw new Error(`Unsupported office file: ${file.name}`);
  const extraction = kind === 'docx' ? await readDocx(file) : await readXlsx(file);
  const entities = await detect(extraction.plainText);
  return {
    kind,
    plainText: extraction.plainText,
    entities,
    unredactable: extraction.unredactable,
    warnings: extraction.warnings,
  };
}

export interface RedactOfficeFileOptions {
  /** The live session; file placeholders join the same map as prompt ones. */
  session: AnonymizationSession;
  /**
   * Entities to redact, from a prior analyzeOfficeFile call (offsets refer to
   * that call's plainText). When omitted, detect is required and is run here.
   */
  entities?: DetectedEntity[];
  /** Detect function; used only when entities were not supplied. */
  detect?: DetectFn;
  /** Accept and strip tracked changes in docx output. Default: true. */
  acceptTrackedChanges?: boolean;
  /**
   * What to do with a supplied entity whose offsets do not match the freshly
   * extracted text (T179, M4). 'throw' (default): raise StaleAnalysisError
   * listing every mismatch before the session is touched, so the host never
   * gets a "redacted" file that still holds the value. 'drop': the historical
   * behaviour, mismatches are filtered out and absent from result.entities.
   */
  onMismatch?: 'throw' | 'drop';
  /**
   * Export even though the package holds parts DocCloak cannot redact
   * (T177). Default false: the writer throws
   * UnsupportedDocumentError('unredactable-parts') with the part names in
   * `details`. With true the parts are copied verbatim and named in
   * result.warnings; hosts pass it only after the user saw the list from
   * analyzeOfficeFile.
   */
  allowUnredactable?: boolean;
}

export interface OfficeRedactionResult {
  kind: OfficeFileKind;
  /** The redacted file; the input file/buffer is never modified. */
  blob: Blob;
  /** Suggested output name: "report.docx" becomes "report.redacted.docx". */
  suggestedName: string;
  /** The entities that were redacted (offsets refer to plainText) */
  entities: DetectedEntity[];
  /** Flat text the detection ran on */
  plainText: string;
  /** The redacted flat text (placeholders applied), for preview UIs */
  redactedText: string;
  /**
   * Writer notes the host must show: one line per unredactable part copied
   * verbatim (allowUnredactable) and per part the layer-zero scrub could not
   * parse. Empty on a clean run.
   */
  warnings: string[];
  /** Parts copied verbatim because allowUnredactable was passed (T177). */
  unredactable: UnredactablePart[];
}

/** "report.docx" -> "report.redacted.docx"; extensionless names get a suffix. */
export function redactedFileName(filename: string): string {
  const dot = filename.lastIndexOf('.');
  if (dot <= 0) return `${filename}.redacted`;
  return `${filename.slice(0, dot)}.redacted${filename.slice(dot)}`;
}

/** True when the entity's offsets land exactly on its value in the text. */
function matchesText(entity: DetectedEntity, plainText: string): boolean {
  return entity.start >= 0
    && entity.end <= plainText.length
    && entity.start < entity.end
    && plainText.slice(entity.start, entity.end) === entity.value;
}

/**
 * Redact a DOCX or XLSX file: extract text, detect (or reuse supplied
 * entities), map every entity through the session, and regenerate the file
 * with placeholders spliced into the XML, formatting preserved and metadata
 * stripped. Placeholder issuing goes through session.anonymize, so a value
 * already seen in a prompt reuses its existing placeholder and vice versa.
 *
 * Fail-closed (T179): supplied entities that do not match this extraction
 * raise StaleAnalysisError unless onMismatch is 'drop'; parts that cannot be
 * redacted raise UnsupportedDocumentError('unredactable-parts') unless
 * allowUnredactable is passed. Both are thrown before the session changes.
 */
export async function redactOfficeFile(
  file: File,
  options: RedactOfficeFileOptions
): Promise<OfficeRedactionResult> {
  const kind = officeFileKind(file.name);
  if (!kind) throw new Error(`Unsupported office file: ${file.name}`);

  const extraction = kind === 'docx' ? await readDocx(file) : await readXlsx(file);
  const plainText = extraction.plainText;

  let entities = options.entities;
  if (!entities) {
    if (!options.detect) {
      throw new Error('redactOfficeFile requires either entities or a detect function');
    }
    entities = await options.detect(plainText);
  }

  const { session } = options;

  // Entities whose offsets do not match this extraction come from a stale
  // analysis (or a different file). Splicing them would corrupt the text and
  // skipping them silently would ship the value (M4), so the default is to
  // refuse; 'drop' keeps the historical filter for hosts that re-detect.
  const mismatched = entities.filter((e) => !matchesText(e, plainText));
  if (mismatched.length > 0 && (options.onMismatch ?? 'throw') === 'throw') {
    throw new StaleAnalysisError(mismatched, entities.length);
  }

  // Map through the session in reading order. Surrogate mode maps PERSON
  // values first, mirroring AnonymizationSession.anonymizeText, so derived
  // surrogates (emails from owner names) stay consistent with prompts.
  const valid = entities
    .filter((e) => matchesText(e, plainText))
    .sort((a, b) => a.start - b.start || a.end - b.end);

  if (session.getMode() === 'surrogate') {
    for (const entity of valid) {
      if (entity.type === 'PERSON') session.anonymize(entity.value, entity.type);
    }
  }

  const replacements = valid.map((entity) => ({
    start: entity.start,
    end: entity.end,
    replacement: session.anonymize(entity.value, entity.type),
  }));

  // Value-level scrubbing (relationship targets, formulas, field instructions
  // and the package-wide layer zero) uses the whole session map, so a value
  // redacted in an earlier prompt is also caught when it hides in a hyperlink
  // target of this file. layerZeroValueReplacements (T172) adds the PERSON
  // name tokens, so a bare surname in a chart cache or custom XML part is
  // caught too. Blanked entries ('________') stay out of the value list.
  const valueReplacements: ValueReplacement[] = layerZeroValueReplacements(
    session.getEntries().filter((entry) => entry.replacement !== '________'),
  );

  let redactedText = plainText;
  for (const repl of [...replacements].sort((a, b) => b.start - a.start)) {
    redactedText = redactedText.slice(0, repl.start) + repl.replacement + redactedText.slice(repl.end);
  }

  const written = kind === 'docx'
    ? await writeAnonymizedDocxWithReport(extraction as DocxExtraction, replacements, valueReplacements, {
        acceptTrackedChanges: options.acceptTrackedChanges ?? true,
        allowUnredactable: options.allowUnredactable ?? false,
      })
    : await writeAnonymizedXlsxWithReport(extraction as XlsxExtraction, replacements, valueReplacements, {
        allowUnredactable: options.allowUnredactable ?? false,
      });

  return {
    kind,
    blob: written.blob,
    suggestedName: redactedFileName(file.name),
    entities: valid,
    plainText,
    redactedText,
    warnings: written.warnings,
    unredactable: extraction.unredactable,
  };
}
